### ISSUE TITLE
Create the footer.

### ISSUE THREAD

**Issue by krittiyaclark** [zero-to-mastery/Keiko-Corp#106] opened 2020-10-02 02:55 UTC
I am going to create the footer.

**Comment by brittneypostma** [comment] 2020-10-02 13:38
merged

**Comment by krittiyaclark** [comment] 2020-10-02 14:00
It does not look like in the design. I am still working on it.

**Comment by MattCSmith** [comment] 2020-10-02 14:06
Agreed, reopening the issue

**Comment by brittneypostma** [comment] 2020-10-02 16:46
Duplicate of #11

**Closed** 2020-10-02 16:46 UTC
Labels: duplicate
