### ISSUE TITLE
Add header with navigation to job-listing.html page

### ISSUE THREAD

**Issue by batistaDev1113** [zero-to-mastery/Keiko-Corp#485] opened 2020-10-05 14:53 UTC
# New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task
Add header with navigation to job-listing.html page

<Detail the problem/task>
I would like to add the navigation to the job-listing.html page.  I assume all pages will have the same navigation as in index.html in order to go back and forth throughout the site?  I will add exactly as it shows on index.html.

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [ x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by batistaDev1113** [comment] 2020-10-05 14:56
@brittneypostma please let me know if I can work on this issue as there no open issue similar to this one.

**Comment by brittneypostma** [comment] 2020-10-05 14:56
There are several files that are not linked. What I would like added is a drop down menu that has links to all of these pages. Can you implement this?

**Comment by batistaDev1113** [comment] 2020-10-05 14:56
I sure can :-)

**Comment by batistaDev1113** [comment] 2020-10-05 14:57
So, is there any specific style/layout ?  Will this remove the way the nav looks right now?

**Comment by brittneypostma** [comment] 2020-10-05 15:01
Maybe it could look something like this 
![image](https://user-images.githubusercontent.com/45889730/95096312-18a52980-06fa-11eb-8aee-fb0d8fb2a32e.png)

**Comment by brittneypostma** [comment] 2020-10-05 15:01
Have all extra links in that More dropdown

**Comment by batistaDev1113** [comment] 2020-10-05 15:04
That is great.  Thanks for the mockup!!

**Comment by batistaDev1113** [comment] 2020-10-05 15:04
I will start work on it right now.  Should I create a different issue ( more specific to this?) or is it ok to submit through this one?

**Comment by brittneypostma** [comment] 2020-10-05 17:11
@batistaDev1113 I realized this is a duplicate of #411, I'm going to close this and comment the mockup over there.

**Closed by brittneypostma** 2020-10-05 17:11 UTC

**Comment by batistaDev1113** [comment] 2020-10-05 17:24
Ok, np!
