### ISSUE TITLE
Email form in never miss an update section.

### ISSUE THREAD

**Issue by girishsontakke** [zero-to-mastery/Keiko-Corp#230] opened 2020-10-02 16:06 UTC
due to conflict in namespace of styling input, form in never miss an update section is not appearing I would like to fix it.

**Comment by brittneypostma** [comment] 2020-10-02 16:10
Duplicate of issue #7

**Comment by girishsontakke** [comment] 2020-10-02 16:14
@brittneypostma While resolving issue #7 someone creates never miss update section but in that section, there is no email form appearing due to conflict in a namespace of styling elements and there are two same headings in that section.
![Screenshot from 2020-10-02 21-44-12](https://user-images.githubusercontent.com/61848210/94945525-70744280-04f8-11eb-81e1-d6b6d14bd41c.png)

**Comment by brittneypostma** [comment] 2020-10-02 16:15
Because it has not been finished and merged in yet.

**Closed by brittneypostma** 2020-10-02 16:15 UTC
Labels: duplicate
