### ISSUE TITLE
Fixing Spacing Below Navbar

### ISSUE THREAD

**Issue by AKSHAYBHOPANI** [zero-to-mastery/Keiko-Corp#303] opened 2020-10-03 08:30 UTC
# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

Fixing Spacing Below Navbar and above the Hero section.

<Detail the problem/task>

There is an un-proportional spacing below the navbar and above the hero section

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by TigerAsH94** [comment] 2020-10-03 09:25
Hey! I would like to try to fix this issue.

**Comment by brittneypostma** [comment] 2020-10-03 13:25
This is a duplicate of #301 that I just merged in and would override those styles.

**Closed** 2020-10-03 13:26 UTC
Labels: duplicate
