### ISSUE TITLE
Fix the slider's checkbox color

### ISSUE THREAD

**Issue by dekisr** [zero-to-mastery/Keiko-Corp#720] opened 2020-10-12 16:57 UTC
# New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task

Current checked slider color does not meet to the Figma instructions.

**Current**:
![Captura de Tela 2020-10-12 às 13 55 11](https://user-images.githubusercontent.com/38201274/95772104-93d68480-0c92-11eb-8575-8eab026e6327.png)

**Figma**:
![Captura de Tela 2020-10-12 às 13 54 03](https://user-images.githubusercontent.com/38201274/95772002-6ee21180-0c92-11eb-8a6b-d2d810082922.png)
![Captura de Tela 2020-10-12 às 13 54 09](https://user-images.githubusercontent.com/38201274/95772007-70133e80-0c92-11eb-81e8-a559fb41617a.png)

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [x] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by brittneypostma** [comment] 2020-10-12 18:27
This is a duplicate of #700 and others, the issue has been fixed.

**Closed by brittneypostma** 2020-10-12 18:27 UTC
