### ISSUE TITLE
Change Layout for navigation on home page

### ISSUE THREAD

**Issue by batistaDev1113** [zero-to-mastery/Keiko-Corp#444] opened 2020-10-04 18:22 UTC
# New Mockup

Please check `assets/css/global.css`, design-assets folder images, and [figma files](https://www.figma.com/file/NY0Do1PFf4xl0ZuSTA1X9U/Keiko-Corp-Hacktoberfest-Project?node-id=2%3A10) for updated style guides. Any new pull request should use the updated color, spacing, and sizing variables.

## No Bootstrap or jQuery

Please refrain from adding Bootstrap or jQuery to the site. These pr's will be closed. They overwrite global styles. Vanilla CSS and JS is way better now anyways 😊

# New Task:

[//]: # 'Please use this template when creating new tasks, issues not using this template will be closed'

#### What is the task
I would like to change the layout for navigation on the home page
<Detail the problem/task>
The navigation looks different than what it looks like on the design mockup.  No border outline should be seen, is not centered like in the mockup, and also the contact btn is the only one that should look like a button with a different color as well.  The contact btn should also appear on the right side of the Dark Mode btn not before.

I have attached images below.
![mockup-design](https://user-images.githubusercontent.com/15971206/95023783-f43f4380-064c-11eb-91a2-f8c9ac7b80d3.png)
![index](https://user-images.githubusercontent.com/15971206/95023795-028d5f80-064d-11eb-8ea2-b8154eda4262.png)

### Who is the task for?

[//]: # 'Place and x in between the brackets to check'

- [X] I created this task for me to complete, I will create a PR soon.
- [ ] I created this task for someone else to claim.
- [ ] I think this is a task that multiple people can do

#### Confirm all of the following:

[//]: # 'Place and x in between the brackets to check'

- [x] I have looked at all the issues currently available and this does not exist or overlap with another ticket

---

[//]: # 'Leave this section in tack, this is to ensure the task is not completed by some one else'

**Comment by batistaDev1113** [comment] 2020-10-04 18:32
@brittneypostma is it ok for me to go ahead and work on this one?

Thank you in advance!

**Comment by brittneypostma** [comment] 2020-10-04 18:34
This is a duplicate of #360, please comment in that thread to work on it.

**Closed by brittneypostma** 2020-10-04 18:34 UTC
